apiVersion: v1
kind: Service
metadata:
  name: static-webpage-service
  namespace: demo-ns
spec:
  type: LoadBalancer
  selector:
    app: static-webpage
  ports:
    - protocol: TCP
      port: 80               # External port
      targetPort: 80        # Port on the job-app container
